pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.10.0'
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        // NewPipe Extractor & Glide
        maven { url "https://jitpack.io" }
    }
    versionCatalogs {
        libs {
            from(files("NewPipeExtractor/gradle/libs.versions.toml"))
        }
    }
}
rootProject.name = "YTTikTokPlayer"
include ':app'
include ":NewPipeExtractor"
include ":NewPipeExtractor:extractor"
include ":NewPipeExtractor:timeago-generator"
