/*
 * KanaePlayer -
 * Copyright (C) 2026 KanaePlayer Team
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed WITHOUT ANY WARRANTY; see the
 * GNU General Public License for more details: <https://www.gnu.org/licenses/>.
 */

package ame.project.kanae.subtitle

import android.content.Context
import android.util.Log
import com.google.gson.Gson
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.OkHttpClient
import okhttp3.Request
import org.schabi.newpipe.extractor.NewPipe
import org.schabi.newpipe.extractor.ServiceList
import org.schabi.newpipe.extractor.stream.StreamInfo
import org.schabi.newpipe.extractor.stream.SubtitlesStream
import java.io.File

/**
 * Fetches subtitle cues for a YouTube video URL using NewPipeExtractor.
 * Caches results as JSON files.
 */
class SubtitleFetcher(
    private val context: Context,
    private val http: OkHttpClient = OkHttpClient()
) {
    companion object {
        private const val TAG = "SubtitleFetcher"
    }

    private val gson = Gson()
    private val cacheDir = File(context.cacheDir, "lyrics_cache").apply { mkdirs() }

    /**
     * @param youtubeUrl  full YouTube watch URL or youtu.be short link
     * @param preferredLang  BCP-47 language code to prefer, e.g. "id", "en"
     * @return [SubtitleResult] with cues + metadata, or null if unavailable
     */
    suspend fun fetch(
        youtubeUrl: String,
        preferredLang: String = "id"
    ): SubtitleResult? = withContext(Dispatchers.IO) {
        val videoId = getVideoId(youtubeUrl)
        if (videoId != null) {
            val cached = loadFromCache(videoId, preferredLang)
            if (cached != null) {
                Log.d(TAG, "Cache hit for $videoId ($preferredLang)")
                return@withContext cached
            }
        }

        try {
            // Ensure we have a proper URL
            val finalUrl = if (youtubeUrl.startsWith("http")) youtubeUrl 
                          else "https://www.youtube.com/watch?v=$youtubeUrl"

            Log.d(TAG, "Fetching StreamInfo for $finalUrl")
            val info = StreamInfo.getInfo(
                NewPipe.getService(ServiceList.YouTube.serviceId),
                finalUrl
            )

            val subtitles: List<SubtitlesStream> = info.subtitles
            if (subtitles.isEmpty()) {
                Log.d(TAG, "No subtitles available for $youtubeUrl")
                return@withContext null
            }

            Log.d(TAG, "Available subtitles: ${subtitles.map { "${it.languageTag}(auto=${it.isAutoGenerated})" }}")

            // Pick the best subtitle stream
            val chosen = pickBest(subtitles, preferredLang)
                ?: return@withContext null

            Log.d(TAG, "Chosen: lang=${chosen.languageTag} auto=${chosen.isAutoGenerated} url=${chosen.content}")

            // Download the VTT content
            val vttContent = downloadVtt(chosen.content)
                ?: return@withContext null

            // Parse into cues
            val cues = VttParser.parse(vttContent)
            if (cues.isEmpty()) {
                Log.w(TAG, "VTT parsed but 0 cues found")
                return@withContext null
            }

            Log.d(TAG, "Parsed ${cues.size} subtitle cues")
            val result = SubtitleResult(
                cues            = cues,
                languageTag     = chosen.languageTag,
                isAutoGenerated = chosen.isAutoGenerated
            )

            // Save to cache
            if (videoId != null) {
                saveToCache(videoId, preferredLang, result)
            }

            result

        } catch (e: Exception) {
            Log.e(TAG, "SubtitleFetcher error: ${e.message}")
            null
        }
    }

    // ── Private helpers ───────────────────────────────────────────────

    private fun getVideoId(url: String): String? {
        return try {
            val patterns = listOf(
                "v=([a-zA-Z0-9_-]{11})",
                "be/([a-zA-Z0-9_-]{11})",
                "shorts/([a-zA-Z0-9_-]{11})",
                "embed/([a-zA-Z0-9_-]{11})"
            )
            for (p in patterns) {
                val match = Regex(p).find(url)
                if (match != null) return match.groupValues[1]
            }
            null
        } catch (e: Exception) {
            null
        }
    }

    private fun loadFromCache(videoId: String, lang: String): SubtitleResult? {
        val file = File(cacheDir, "${videoId}_$lang.json")
        if (!file.exists()) return null
        return try {
            val json = file.readText()
            gson.fromJson(json, SubtitleResult::class.java)
        } catch (e: Exception) {
            Log.e(TAG, "Failed to load cache: ${e.message}")
            file.delete()
            null
        }
    }

    private fun saveToCache(videoId: String, lang: String, result: SubtitleResult) {
        try {
            val file = File(cacheDir, "${videoId}_$lang.json")
            file.writeText(gson.toJson(result))
            Log.d(TAG, "Saved lyrics to cache: ${file.absolutePath}")
        } catch (e: Exception) {
            Log.e(TAG, "Failed to save cache: ${e.message}")
        }
    }

    private fun pickBest(
        list: List<SubtitlesStream>,
        preferredLang: String
    ): SubtitlesStream? {
        val lang = preferredLang.lowercase()

        // 1. Manual subtitle in preferred language
        list.firstOrNull { !it.isAutoGenerated && it.languageTag.lowercase().startsWith(lang) }
            ?.let { return it }

        // 2. Any manual subtitle
        list.firstOrNull { !it.isAutoGenerated }
            ?.let { return it }

        // 3. Auto-generated in preferred language
        list.firstOrNull { it.isAutoGenerated && it.languageTag.lowercase().startsWith(lang) }
            ?.let { return it }

        // 4. Any auto-generated
        return list.firstOrNull { it.isAutoGenerated }
    }

    private fun downloadVtt(url: String): String? {
        return try {
            // YouTube API defaults to TTML if fmt is not specified or set to ttml.
            // We force VTT format so our VttParser can read it.
            val vttUrl = if (url.contains("youtube.com/api/timedtext") && !url.contains("fmt=vtt")) {
                if (url.contains("fmt=ttml")) url.replace("fmt=ttml", "fmt=vtt")
                else if (url.contains("?")) "$url&fmt=vtt"
                else "$url?fmt=vtt"
            } else url

            Log.d(TAG, "Downloading subtitles from: $vttUrl")
            val req  = Request.Builder().url(vttUrl)
                .header("User-Agent", "Mozilla/5.0")
                .build()
            http.newCall(req).execute().use { resp ->
                if (resp.isSuccessful) resp.body?.string()
                else { Log.e(TAG, "VTT download failed: ${resp.code}"); null }
            }
        } catch (e: Exception) {
            Log.e(TAG, "VTT download error: ${e.message}")
            null
        }
    }
}

/**
 * Result of a successful subtitle fetch.
 */
data class SubtitleResult(
    val cues: List<SubtitleCue>,
    val languageTag: String,
    val isAutoGenerated: Boolean
) {
    /**
     * Returns the cue active at [positionMs], or null if none.
     * Uses binary search for O(log n) lookup.
     */
    fun cueAt(positionMs: Long): SubtitleCue? {
        var lo = 0; var hi = cues.size - 1
        while (lo <= hi) {
            val mid = (lo + hi) ushr 1
            val c   = cues[mid]
            when {
                positionMs < c.startMs -> hi = mid - 1
                positionMs > c.endMs   -> lo = mid + 1
                else                   -> return c
            }
        }
        return null
    }
}
